### ISSUE TITLE
What License governs this Code?

### ISSUE THREAD

**Issue by thron7** [fpinjava/fpinjava#16]
I didn't find any license statement in this repo. Particularly, is it ok to include code from this repo in commercial projects?

**Comment by pysaumont** [comment]
You can do what you want excepted claiming copyright. This means that if
your software isn’t free, you have to indicate where the copied part comes
from.

**Comment by thron7** [comment]
Great, thanks. Consider[ adding a LICENSE.txt](https://choosealicense.com/) to this end.
