### ISSUE TITLE
Duplicate source folder 

### ISSUE THREAD

**Issue by thescalarian** [fpinjava/fpinjava#5]
Following the path fpinjava/fpinjava-parent/fpinjava-common/ there is a folder src/main/java/com/fpinjava/common/ that contains nearly the same classes as in the parent directory. Therefore IntelliJ complains about duplicate classes.

**Comment by pysaumont** [comment]
Hi,

Can you be more precise about the duplicate classes? I guess that what you call the parent directory is fpinjava/fpinjava-parent. So duplicate class would mean that there is some class like 

fpinjava/fpinjava-parent/fpinjava-common/src/main/java/com/fpinjava/common/... 

with the same class 

in fpinjava/fpinjava-parent/src/main/java/com/fpinjava/common/...

Is that correct? Can you give a precise example? I do not see any src folder in fpinjava/fpinjava-parent.

I guess it is a problem about IntelliJ project configuration. Did you import the project as a Gradle project?

**Comment by thescalarian** [comment]
Hi,

no it's in the repository, you can see it online

follow the links please

https://github.com/fpinjava/fpinjava/tree/master/fpinjava-parent/fpinjava-common/common

https://github.com/fpinjava/fpinjava/tree/master/fpinjava-parent/fpinjava-common/src/main/java/com/fpinjava/common

**Comment by thescalarian** [comment]
I played around a little more (I'm used to maven not to gradle) and came to the conclusion that the readme is not complete. To get some sensible results with Idea I had to do the following.

* Clone the repo
* Execute gradlew.bat
* Execute gradlew idea
* Fire up IntelliJ and just open the path where the project resides instead of importing it

After that, IntelliJ didn't complain about the duplicate files any longer, nevertheless I think the path https://github.com/fpinjava/fpinjava/tree/master/fpinjava-parent/fpinjava-common/common can be dropped in favor of https://github.com/fpinjava/fpinjava/tree/master/fpinjava-parent/fpinjava-common/src/main/java/com/fpinjava/common.

Can you confirm if my steps are the way it should be done if someone is using IntelliJ?

**Comment by pysaumont** [comment]
This way should work too (obviously it does!) but it is not the simplest way. You are using Gradle and the Gradle Idea plugin to create an Idea project that you then open with Idea, instead of importing the Gradle project with Idea, letting Idea create the Idea project. Both approachs work but the first one is slightly more complex. Moreover, I would have supposed Idea being better than Gradle at creating Idea projects ;-)

Something is quite strange: the first directory does not exist in my local repo, and Git says I am up to date, so there is not evident way to remove it! I am going to investigate this, probably trying to do a fresh clone an removing the directory before committing an pushing back.

**Comment by thescalarian** [comment]
IntelliJ doesn't seem to recognize that it's a gradle project at all. It just talks about the the library import gradle-stuff. But after the import the modules are all named like main1, main2 and so on.

I pushed a branch to my fork https://github.com/thescalarian/fpinjava/tree/issue-5

**Comment by pysaumont** [comment]
Do you have the Gradle plugin installed in IntelliJ? I think this plugin installed by default, but I may be wrong. When importing, you should have two choices in the Import Project dialog box:

- Create project from existing sources
- Import project from external model

Selecting the second, you should have three options available:

- Eclipse
- Gradle
- Maven

You should of course select Gradle

**Comment by pysaumont** [comment]
Anyway, I have removed the duplicated directory. I was using the Github Mac Git client for this project, and it seems not to work correctly. I switched back to command line.

**Comment by thescalarian** [comment]
You are right, I should have enabled the gradle plugin. I remember it was one of the first plugins I disabled because I don't use gradle. It works now. ;)
